{% set name = "pywhip" %}
{% set version = "0.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pywhip-{{ version }}.tar.gz
  sha256: ee30d5182e34bbeb54dc6db06a784a770c41eff2f945b5ab09653821eba5f471

build:
  number: 0
  noarch: python
  entry_points:
    - whip_csv=pywhip.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - pytest-runner
  run:
    - python >=3.6
    - click >=6.0
    - python-dwca-reader ==0.13.0
    - cerberus ==1.3.4
    - pyaml ==17.12.1
    - rfc3987 ==1.3.7
    - python-dateutil ==2.7.2
    - jinja2

test:
  imports:
    - pywhip
  commands:
    - pip check
    - whip_csv --help
  requires:
    - pip

about:
  home: https://github.com/inbo/pywhip
  summary: Python package to validate data against whip specifications
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
